### ISSUE TITLE
"stix-shifter-modules-sentinelone not properly executing due to sentinelone connector error => Error when converting STIX pattern to data source query: [Errno 2] No such file or directory"  when using default configuration and set up

### ISSUE THREAD

**Issue by tavalkyansant** [opencybersecurityalliance/stix-shifter#1032] opened 2022-07-07 18:20 UTC
**Describe the bug**
Using the stix-shifter-modules-sentinelone module is broken due to the following:
`"error": "sentinelone connector error => Error when converting STIX pattern to data source query: [Errno 2] No such file or directory: '/opt/tljh/user/lib/python3.9/site-packages/stix_shifter_utils/modules/base/stix_translation/json/operators.json'"`
**To Reproduce**
1. Install the stix-shifter-modules-sentinelone package
2. execute `stix-shifter mapping sentinelone` and observe the error: 
```
(virtualenv) PS C:\Users\snipped\snipped\stix-shifter> stix-shifter mapping sentinelone
 2022-06-23 11:27:51,762 stix_shifter.stix_translation.stix_translation ERROR    [Errno 2] No such file or directory: 'C:Users\\snipped\\snipped\\stix-shifter\\virtualenv\\lib\\site-packages\\stix_shifter_utils\\modules\\base\\stix_translation\\json\\operators.json'   
 2022-06-23 11:27:51,763 stix_shifter.stix_translation.stix_translation ERROR    Caught exception: [Errno 2] No such file or directory: 'C:Users\\snipped\\snipped\\stix-shifter\\virtualenv\\lib\\site-packages\\stix_shifter_utils\\modules\\base\\stix_translation\\json\\operators.json' <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\lib\site-packages\stix_shifter\stix_translation\stix_translation.py", line 61, in translate
    entry_point = connector_module.EntryPoint(options=validated_options)
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\lib\site-packages\stix_shifter_modules\sentinelone\entry_point.py", line 11, 
in __init__
    self.setup_translation_simple(dialect_default='default')
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\lib\site-packages\stix_shifter_utils\utils\base_entry_point.py", line 108, in setup_translation_simple
    self.add_dialect(dialect, query_translator=query_translator, results_translator=results_translator,
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\lib\site-packages\stix_shifter_utils\utils\base_entry_point.py", line 88, in 
add_dialect
    query_translator = self.create_default_query_translator(dialect)
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\lib\site-packages\stix_shifter_utils\utils\base_entry_point.py", line 117, in create_default_query_translator
    query_translator = module.QueryTranslator(self.__options, dialect, mapping_filepath)
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\lib\site-packages\stix_shifter_utils\modules\base\stix_translation\base_query_translator.py", line 26, in __init__
    self.map_operator = self.fetch_operators(basepath, dialect, options)
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\lib\site-packages\stix_shifter_utils\modules\base\stix_translation\base_query_translator.py", line 40, in fetch_operators
    return self.read_json(operator_file_path, options)
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\lib\site-packages\stix_shifter_utils\modules\base\stix_translation\base_query_translator.py", line 29, in read_json
    return helper_read_json(filepath, options)
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\lib\site-packages\stix_shifter_utils\utils\file_helper.py", line 37, in read_json
    with open(file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:Users\\snipped\\snipped\\stix-shifter\\virtualenv\\lib\\site-packages\\stix_shifter_utils\\modules\\base\\stix_translation\\json\\operators.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\users\snipped\appdata\local\programs\pythoncodingpack\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\users\snipped\appdata\local\programs\pythoncodingpack\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\Scripts\stix-shifter.exe\__main__.py", line 7, in <module>
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\lib\site-packages\stix_shifter\scripts\stix_shifter.py", line 326, in main   
    result = translation.translate(args.module, stix_translation.MAPPING, None, None, options=options)
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\lib\site-packages\stix_shifter\stix_translation\stix_translation.py", line 143, in translate
    ErrorResponder.fill_error(response, message_struct={'exception': ex}, connector=module)
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\lib\site-packages\stix_shifter_utils\utils\error_response.py", line 117, in fill_error
    ErrorResponder.call_module_error_mapper(message_struct, return_object, connector)
  File "C:\Users\snipped\snipped\stix-shifter\virtualenv\lib\site-packages\stix_shifter_utils\utils\error_response.py", line 127, in call_module_error_mapper
    module_path = 'stix_shifter_modules.' + caller_module_name[0] + '.' + caller_module_name[1] + '.error_mapper'
IndexError: list index out of range
```
3. Furthermore, attempting to execute a generic stix-shifter query with intent to translate to sentinelone query: 
`stix-shifter translate sentinelone query "{}" "[url:value = 'http://www.testaddress.com/'] OR [ipv4-addr:value = '192.168.122.84']"`
returns the error:
`"error": "sentinelone connector error => Error when converting STIX pattern to data source query: [Errno 2] No such file or directory: '/opt/tljh/user/lib/python3.9/site-packages/stix_shifter_utils/modules/base/stix_translation/json/operators.json'"`

**Expected behavior**
A translation from a stix query to a sentinel one query
for example I created a workaround by  pasting the operators file from the s1 module into  site-packages/stix_shifter_utils/modules/base/stix_translation/json/ with json being a new dir, and operators.json being a new file to receive the expected result:
![image](https://user-images.githubusercontent.com/68788972/177841772-1021e47b-5fa7-4b7d-b4d6-2160d15f74a9.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10, ubuntu22.04-LTS, Pop OS! v20.04-LTS]
 - Browser [vscode, bash, jupyter with python 3.9 and 3.86]

**Comment by tavalkyansant** [comment] 2022-07-07 18:35
> Thanks for opening this. It looks like some of the CLI commands that aren't used in the regular query flow are misbehaving and will need to be fixed.
Hi, no problem.
Something I should clarify - trying to use it a kestrel session/huntbook would return the same error.

**Comment by mdazam1942** [comment] 2022-07-15 18:39
@tavalkyansant I couldn't reproduce the error. I installed a fresh copy of the latest version of the stix-shifter packages in python 3.6 and python 3.9 virtual env. 

Can you post the package versions of the stix-shifter packages? my be just output of this command-
`pip freeze|grep stix-shifter`

Need to verify if any specific version is causing the error.

**Comment by tavalkyansant** [comment] 2022-08-09 20:17
@mdazam1942: Hello. I previously made change on my internal end which resolved the error after reporting. I tried to reproduce the error given your environment etc to replicate the issue after you said you could not. Strangely, I could not resolve it either in a fresh environment. It worked as it was expected to. I guess this issue could be closed. Not sure what was happening.

**Comment by mdazam1942** [comment] 2022-08-12 15:51
Thanks for the update. Closing it.

**Closed by mdazam1942** 2022-08-12 15:51 UTC
